package com.englishcoach.app

object StoryLibrary {
    val stories: List<Story> = listOf(
        Story(
            id="a1-wallet", level=CefrLevel.A1, title="The Lost Wallet", category="Günlük Hayat", emoji="👛", description="Aynı hikâyenin A1 sürümü: kısa ve çok basit.",
            sentences=listOf(StorySentence("Mina is in a café.", "Mina bir kafede."), StorySentence("She has a small black wallet.", "Küçük siyah bir cüzdanı var."), StorySentence("She drinks coffee and leaves.", "Kahve içer ve çıkar."), StorySentence("At home, she looks for her wallet.", "Evde cüzdanını arar."), StorySentence("It isn't in her bag.", "Çantasında değildir."), StorySentence("Mina goes back to the café.", "Mina kafeye geri gider."), StorySentence("The waiter has her wallet.", "Garsonun cüzdanı ondadır."), StorySentence("Mina is very happy.", "Mina çok mutludur.")),
            vocabulary=listOf(VocabItem("wallet", "cüzdan", "She has a small black wallet.", "Küçük siyah bir cüzdanı var."), VocabItem("bag", "çanta", "It isn't in her bag.", "Çantasında değildir."), VocabItem("waiter", "garson", "The waiter has her wallet.", "Garsonun cüzdanı ondadır."), VocabItem("go back", "geri gitmek", "Mina goes back to the café.", "Mina kafeye geri gider.")),
            questions=listOf(PracticeQuestion("Where is Mina at the beginning?", listOf("At school", "In a café", "At the airport", "At work"), 1, "Hikâye Mina’nın kafede olmasıyla başlıyor.", "story comprehension"), PracticeQuestion("Who has the wallet?", listOf("The waiter", "Her friend", "A driver", "Nobody"), 0, "Garson cüzdanı bulmuştur.", "story comprehension"))
        ),
        Story(
            id="a2-wallet", level=CefrLevel.A2, title="The Lost Wallet", category="Günlük Hayat", emoji="👛", description="Aynı hikâyenin A2 sürümü: geçmiş zaman ve daha fazla detay.",
            sentences=listOf(StorySentence("Mina stopped at a small café after work.", "Mina işten sonra küçük bir kafeye uğradı."), StorySentence("She ordered a coffee and paid with cash.", "Bir kahve söyledi ve nakit ödedi."), StorySentence("When she arrived home, she noticed that her wallet was missing.", "Eve vardığında cüzdanının kayıp olduğunu fark etti."), StorySentence("She checked her bag twice but could not find it.", "Çantasını iki kez kontrol etti ama bulamadı."), StorySentence("Then she remembered the café.", "Sonra kafeyi hatırladı."), StorySentence("She went back and asked the waiter for help.", "Geri gidip garsondan yardım istedi."), StorySentence("Luckily, someone had found the wallet under her chair.", "Neyse ki biri cüzdanı sandalyesinin altında bulmuştu."), StorySentence("Nothing was missing.", "Hiçbir şey eksik değildi.")),
            vocabulary=listOf(VocabItem("noticed", "fark etti", "When she arrived home, she noticed that her wallet was missing.", "Eve vardığında cüzdanının kayıp olduğunu fark etti."), VocabItem("missing", "kayıp/eksik", "When she arrived home, she noticed that her wallet was missing.", "Eve vardığında cüzdanının kayıp olduğunu fark etti."), VocabItem("luckily", "neyse ki", "Luckily, someone had found the wallet under her chair.", "Neyse ki biri cüzdanı sandalyesinin altında bulmuştu."), VocabItem("under", "altında", "Luckily, someone had found the wallet under her chair.", "Neyse ki biri cüzdanı sandalyesinin altında bulmuştu.")),
            questions=listOf(PracticeQuestion("Why did Mina return to the café?", listOf("To buy food", "To find her wallet", "To meet a friend", "To work"), 1, "Cüzdanını aramak için döndü.", "story comprehension"), PracticeQuestion("Where was the wallet found?", listOf("On the table", "Under her chair", "In the kitchen", "Outside"), 1, "Cüzdan sandalyesinin altında bulundu.", "story comprehension"))
        ),
        Story(
            id="b1-wallet", level=CefrLevel.B1, title="The Lost Wallet", category="Gizem", emoji="👛", description="Aynı olayın B1 sürümü: olay örgüsü ve tahmin.",
            sentences=listOf(StorySentence("After a long day at work, Mina decided to relax at a café near the station.", "Uzun bir iş gününden sonra Mina istasyon yakınındaki bir kafede dinlenmeye karar verdi."), StorySentence("She stayed for almost an hour, reading messages and planning her weekend.", "Neredeyse bir saat kaldı, mesajlarını okudu ve hafta sonunu planladı."), StorySentence("Later that evening, she realized her wallet had disappeared.", "O akşam daha sonra cüzdanının kaybolduğunu fark etti."), StorySentence("She felt nervous because her cards and ID were inside.", "Kartları ve kimliği içinde olduğu için gerildi."), StorySentence("Before cancelling her cards, she called the café.", "Kartlarını iptal etmeden önce kafeyi aradı."), StorySentence("The manager asked her to describe the wallet.", "Müdür cüzdanı tarif etmesini istedi."), StorySentence("A customer had handed it in a few minutes after Mina left.", "Bir müşteri Mina çıktıktan birkaç dakika sonra cüzdanı teslim etmişti."), StorySentence("Relieved, Mina returned to collect it and thanked everyone.", "Rahatlayan Mina cüzdanı almaya döndü ve herkese teşekkür etti.")),
            vocabulary=listOf(VocabItem("realized", "farkına vardı", "Later that evening, she realized her wallet had disappeared.", "O akşam daha sonra cüzdanının kaybolduğunu fark etti."), VocabItem("disappeared", "kayboldu", "Later that evening, she realized her wallet had disappeared.", "O akşam daha sonra cüzdanının kaybolduğunu fark etti."), VocabItem("handed in", "teslim etti", "A customer had handed it in a few minutes after Mina left.", "Bir müşteri Mina çıktıktan birkaç dakika sonra cüzdanı teslim etmişti."), VocabItem("relieved", "rahatlamış", "Relieved, Mina returned to collect it and thanked everyone.", "Rahatlayan Mina cüzdanı almaya döndü ve herkese teşekkür etti.")),
            questions=listOf(PracticeQuestion("What was Mina going to do before calling?", listOf("Cancel her cards", "Call the police", "Go home", "Buy a new bag"), 0, "Kartlarını iptal etmeyi düşünüyordu.", "story comprehension"), PracticeQuestion("How did the wallet return?", listOf("A customer handed it in", "She found it at home", "The police found it", "It was mailed"), 0, "Bir müşteri kafeye teslim etti.", "story comprehension"))
        ),
        Story(
            id="b2-wallet", level=CefrLevel.B2, title="The Lost Wallet", category="Gizem", emoji="👛", description="Aynı hikâyenin B2 sürümü: doğal ifadeler ve daha ince detay.",
            sentences=listOf(StorySentence("Mina had barely settled in for the evening when she noticed her wallet was nowhere to be found.", "Mina akşam için daha yeni yerleşmişti ki cüzdanının hiçbir yerde olmadığını fark etti."), StorySentence("Her first instinct was to assume she had dropped it on the way home.", "İlk içgüdüsü eve gelirken düşürdüğünü varsaymak oldu."), StorySentence("She retraced her steps mentally and remembered paying at a café near the station.", "Adımlarını zihninde geri takip etti ve istasyon yakınındaki kafede ödeme yaptığını hatırladı."), StorySentence("Rather than immediately blocking every card, she phoned the café first.", "Tüm kartları hemen bloke etmek yerine önce kafeyi aradı."), StorySentence("The manager sounded cautious and asked her to identify a few items inside.", "Müdür temkinli konuştu ve içindeki birkaç şeyi tarif etmesini istedi."), StorySentence("Once she did, he confirmed that a customer had handed the wallet in.", "Tarif edince bir müşterinin cüzdanı teslim ettiğini doğruladı."), StorySentence("What had felt like a disaster turned into a reminder that strangers can be remarkably kind.", "Felaket gibi hissettiren şey yabancıların ne kadar nazik olabileceğini hatırlatan bir olaya dönüştü.")),
            vocabulary=listOf(VocabItem("nowhere to be found", "hiçbir yerde bulunamamak", "Mina had barely settled in for the evening when she noticed her wallet was nowhere to be found.", "Mina akşam için daha yeni yerleşmişti ki cüzdanının hiçbir yerde olmadığını fark etti."), VocabItem("instinct", "içgüdü", "Her first instinct was to assume she had dropped it on the way home.", "İlk içgüdüsü eve gelirken düşürdüğünü varsaymak oldu."), VocabItem("retrace", "geri izlemek", "She retraced her steps mentally and remembered paying at a café near the station.", "Adımlarını zihninde geri takip etti ve istasyon yakınındaki kafede ödeme yaptığını hatırladı."), VocabItem("remarkably", "dikkat çekici biçimde", "What had felt like a disaster turned into a reminder that strangers can be remarkably kind.", "Felaket gibi hissettiren şey yabancıların ne kadar nazik olabileceğini hatırlatan bir olaya dönüştü.")),
            questions=listOf(PracticeQuestion("Why did the manager ask about items inside?", listOf("To sell them", "To verify ownership", "To make a list for police", "To charge a fee"), 1, "Cüzdanın gerçekten Mina’ya ait olduğunu doğrulamak istedi.", "story comprehension"), PracticeQuestion("What is the final idea?", listOf("The city is dangerous", "Cards are unnecessary", "Strangers can be kind", "Cafés are expensive"), 2, "Son cümlede yabancıların iyiliği vurgulanıyor.", "story comprehension"))
        ),
        Story(
            id="c1-wallet", level=CefrLevel.C1, title="The Lost Wallet", category="Gizem", emoji="👛", description="Aynı olayın C1 sürümü: nüans, çıkarım ve stil.",
            sentences=listOf(StorySentence("It was only after Mina had changed into comfortable clothes that the absence of her wallet registered.", "Mina rahat kıyafetlerini giydikten sonra ancak cüzdanının yokluğu zihninde yer etti."), StorySentence("A familiar wave of panic set in as she pictured the tedious process of replacing cards and documents.", "Kartları ve belgeleri yenilemenin zahmetli sürecini hayal ederken tanıdık bir panik dalgası başladı."), StorySentence("Trying not to overreact, she reconstructed the evening in reverse.", "Aşırı tepki vermemeye çalışarak akşamı tersten yeniden kurdu."), StorySentence("The café near the station was the last place she distinctly remembered using the wallet.", "Cüzdanı kullandığını net hatırladığı son yer istasyon yakınındaki kafeydi."), StorySentence("To her relief, the manager said an elderly customer had handed it in almost immediately.", "Rahatlamasına neden olacak şekilde müdür, yaşlı bir müşterinin cüzdanı neredeyse hemen teslim ettiğini söyledi."), StorySentence("He nevertheless asked several verification questions before agreeing to return it.", "Yine de iade etmeyi kabul etmeden önce birkaç doğrulama sorusu sordu."), StorySentence("The incident left Mina slightly embarrassed by how quickly she had imagined the worst.", "Olay Mina’yı en kötüsünü ne kadar hızlı hayal ettiğinden dolayı biraz utandırdı.")),
            vocabulary=listOf(VocabItem("register", "farkına varılmak/zihne oturmak", "It was only after Mina had changed into comfortable clothes that the absence of her wallet registered.", "Mina rahat kıyafetlerini giydikten sonra ancak cüzdanının yokluğu zihninde yer etti."), VocabItem("tedious", "zahmetli ve sıkıcı", "A familiar wave of panic set in as she pictured the tedious process of replacing cards and documents.", "Kartları ve belgeleri yenilemenin zahmetli sürecini hayal ederken tanıdık bir panik dalgası başladı."), VocabItem("reconstruct", "yeniden kurmak", "Trying not to overreact, she reconstructed the evening in reverse.", "Aşırı tepki vermemeye çalışarak akşamı tersten yeniden kurdu."), VocabItem("nevertheless", "yine de", "He nevertheless asked several verification questions before agreeing to return it.", "Yine de iade etmeyi kabul etmeden önce birkaç doğrulama sorusu sordu.")),
            questions=listOf(PracticeQuestion("What does 'reconstructed the evening in reverse' imply?", listOf("She repeated the evening", "She mentally reviewed events backwards", "She forgot everything", "She wrote a story"), 1, "Olayları sondan başa zihninde gözden geçirdi.", "story comprehension"), PracticeQuestion("Why was Mina embarrassed?", listOf("She lost money", "She blamed the manager", "She imagined the worst very quickly", "She forgot her name"), 2, "Son cümlede bunu açıkça söylüyor.", "story comprehension"))
        ),
        Story(
            id="c2-wallet", level=CefrLevel.C2, title="The Lost Wallet", category="Gizem", emoji="👛", description="Aynı olayın C2 sürümü: yoğun, doğal ve nüanslı anlatım.",
            sentences=listOf(StorySentence("The missing wallet announced itself not through any dramatic discovery, but through the mundane act of reaching for a card that was no longer there.", "Kayıp cüzdan kendini dramatik bir keşifle değil, artık orada olmayan bir karta uzanmak gibi sıradan bir hareketle belli etti."), StorySentence("For a few seconds, Mina entertained every unhelpful possibility at once: theft, carelessness, bureaucratic chaos.", "Birkaç saniye boyunca Mina tüm faydasız ihtimalleri aynı anda düşündü: hırsızlık, dikkatsizlik, bürokratik karmaşa."), StorySentence("Then practicality reasserted itself.", "Sonra pratik düşünce yeniden hakim oldu."), StorySentence("She traced the evening back to a café where she had paid shortly before heading home.", "Akşamı eve dönmeden kısa süre önce ödeme yaptığı kafeye kadar geri izledi."), StorySentence("The manager, commendably discreet, refused to confirm anything until she described the contents in detail.", "Takdire değer biçimde ihtiyatlı davranan müdür, içeriği ayrıntılı tarif edene kadar hiçbir şeyi doğrulamayı reddetti."), StorySentence("Only then did he reveal that another customer had found it beneath a chair and handed it in.", "Ancak o zaman başka bir müşterinin cüzdanı sandalyenin altında bulup teslim ettiğini açıkladı."), StorySentence("The episode was trivial in consequence but oddly restorative in effect: her faith in strangers had been nudged upward.", "Olay sonuçları bakımından önemsizdi ama etkisi garip biçimde iyileştiriciydi: yabancılara güveni biraz artmıştı.")),
            vocabulary=listOf(VocabItem("mundane", "sıradan/gündelik", "The missing wallet announced itself not through any dramatic discovery, but through the mundane act of reaching for a card that was no longer there.", "Kayıp cüzdan kendini dramatik bir keşifle değil, artık orada olmayan bir karta uzanmak gibi sıradan bir hareketle belli etti."), VocabItem("reassert", "yeniden hakim olmak", "Then practicality reasserted itself.", "Sonra pratik düşünce yeniden hakim oldu."), VocabItem("commendably", "takdire değer biçimde", "The manager, commendably discreet, refused to confirm anything until she described the contents in detail.", "Takdire değer biçimde ihtiyatlı davranan müdür, içeriği ayrıntılı tarif edene kadar hiçbir şeyi doğrulamayı reddetti."), VocabItem("restorative", "iyileştirici/yenileyici", "The episode was trivial in consequence but oddly restorative in effect: her faith in strangers had been nudged upward.", "Olay sonuçları bakımından önemsizdi ama etkisi garip biçimde iyileştiriciydi: yabancılara güveni biraz artmıştı.")),
            questions=listOf(PracticeQuestion("Why is the manager described as 'discreet'?", listOf("He hid the wallet", "He protected information until ownership was verified", "He left the café", "He spoke loudly"), 1, "Kimliği doğrulamadan bilgi vermemesi ihtiyatlı davranış olarak sunuluyor.", "story comprehension"), PracticeQuestion("What changed most for Mina?", listOf("Her finances", "Her travel plan", "Her trust in strangers", "Her job"), 2, "Son ifade yabancılara güveninin arttığını söylüyor.", "story comprehension"))
        ),
        Story(
            id="a1-city", level=CefrLevel.A1, title="My New City", category="Şehir & Yaşam", emoji="🏙️", description="A1 seviyesinde şehir ve aidiyet temalı okuma.",
            sentences=listOf(StorySentence("Leo is new in the city.", "Leo şehirde yenidir."), StorySentence("He lives near a park.", "Bir parkın yakınında yaşar."), StorySentence("There is a bakery next to his house.", "Evinin yanında bir fırın vardır."), StorySentence("He buys bread every morning.", "Her sabah ekmek alır."), StorySentence("He likes his new city.", "Yeni şehrini sever.")),
            vocabulary=listOf(VocabItem("new", "yeni", "Leo is new in the city.", "Leo şehirde yenidir."), VocabItem("near", "yakın", "He lives near a park.", "Bir parkın yakınında yaşar."), VocabItem("bakery", "fırın", "There is a bakery next to his house.", "Evinin yanında bir fırın vardır.")),
            questions=listOf(PracticeQuestion("What is near Leo's home?", listOf("A beach", "A park", "An airport", "A school"), 1, "Evinin yakınında park var.", "story comprehension"))
        ),
        Story(
            id="a2-city", level=CefrLevel.A2, title="A Week in a New City", category="Şehir & Yaşam", emoji="🏙️", description="A2 seviyesinde şehir ve aidiyet temalı okuma.",
            sentences=listOf(StorySentence("Leo moved to a new city for work.", "Leo iş için yeni bir şehre taşındı."), StorySentence("During his first week, he explored the neighbourhood.", "İlk haftasında mahalleyi keşfetti."), StorySentence("He found a quiet park and a friendly bakery.", "Sakin bir park ve samimi bir fırın buldu."), StorySentence("The baker started remembering his usual order.", "Fırıncı onun her zamanki siparişini hatırlamaya başladı."), StorySentence("The city slowly began to feel like home.", "Şehir yavaş yavaş ev gibi hissettirmeye başladı.")),
            vocabulary=listOf(VocabItem("moved", "taşındı", "Leo moved to a new city for work.", "Leo iş için yeni bir şehre taşındı."), VocabItem("neighbourhood", "mahalle", "During his first week, he explored the neighbourhood.", "İlk haftasında mahalleyi keşfetti."), VocabItem("usual", "her zamanki", "The baker started remembering his usual order.", "Fırıncı onun her zamanki siparişini hatırlamaya başladı.")),
            questions=listOf(PracticeQuestion("Why did Leo move?", listOf("For work", "For school", "For a holiday", "For family"), 0, "İş için taşındı.", "story comprehension"))
        ),
        Story(
            id="b1-city", level=CefrLevel.B1, title="Learning to Belong", category="Şehir & Yaşam", emoji="🏙️", description="B1 seviyesinde şehir ve aidiyet temalı okuma.",
            sentences=listOf(StorySentence("Moving for a new job sounded exciting until Leo actually arrived.", "Yeni bir iş için taşınmak Leo gerçekten gelene kadar heyecan verici geliyordu."), StorySentence("At first, he knew nobody and spent most evenings alone.", "İlk başta kimseyi tanımıyordu ve akşamların çoğunu yalnız geçiriyordu."), StorySentence("He made a habit of visiting the same bakery and park.", "Aynı fırını ve parkı ziyaret etmeyi alışkanlık haline getirdi."), StorySentence("Small conversations gradually turned familiar faces into friends.", "Küçük sohbetler yavaş yavaş tanıdık yüzleri arkadaşlara dönüştürdü."), StorySentence("By the end of the month, the city no longer felt temporary.", "Ayın sonunda şehir artık geçici hissettirmiyordu.")),
            vocabulary=listOf(VocabItem("belong", "ait hissetmek", "Moving for a new job sounded exciting until Leo actually arrived.", "Yeni bir iş için taşınmak Leo gerçekten gelene kadar heyecan verici geliyordu."), VocabItem("habit", "alışkanlık", "He made a habit of visiting the same bakery and park.", "Aynı fırını ve parkı ziyaret etmeyi alışkanlık haline getirdi."), VocabItem("gradually", "yavaş yavaş", "Small conversations gradually turned familiar faces into friends.", "Küçük sohbetler yavaş yavaş tanıdık yüzleri arkadaşlara dönüştürdü.")),
            questions=listOf(PracticeQuestion("What helped Leo feel at home?", listOf("Buying a car", "Repeated small social contacts", "Changing jobs", "Leaving the city"), 1, "Düzenli küçük sohbetler ve tanıdık yüzler yardımcı oldu.", "story comprehension"))
        ),
        Story(
            id="b2-city", level=CefrLevel.B2, title="Finding a Rhythm", category="Şehir & Yaşam", emoji="🏙️", description="B2 seviyesinde şehir ve aidiyet temalı okuma.",
            sentences=listOf(StorySentence("Leo had expected the practical side of moving to be difficult; he had underestimated the emotional side.", "Leo taşınmanın pratik kısmının zor olmasını beklemişti; duygusal kısmını hafife almıştı."), StorySentence("Without familiar routines, even simple evenings felt strangely empty.", "Tanıdık rutinler olmayınca basit akşamlar bile garip biçimde boş geliyordu."), StorySentence("Instead of waiting to feel settled, he deliberately built a routine around a local bakery, a park and a weekend language club.", "Yerleşmiş hissetmeyi beklemek yerine yerel bir fırın, park ve hafta sonu dil kulübü etrafında bilinçli bir rutin kurdu."), StorySentence("Those repeated encounters gave the city a sense of continuity.", "Bu tekrarlanan karşılaşmalar şehre bir devamlılık hissi verdi."), StorySentence("Belonging, he discovered, was less a feeling that arrived and more a habit that was built.", "Ait olmanın gelen bir histen çok inşa edilen bir alışkanlık olduğunu keşfetti.")),
            vocabulary=listOf(VocabItem("underestimate", "hafife almak", "Leo had expected the practical side of moving to be difficult; he had underestimated the emotional side.", "Leo taşınmanın pratik kısmının zor olmasını beklemişti; duygusal kısmını hafife almıştı."), VocabItem("deliberately", "bilinçli olarak", "Instead of waiting to feel settled, he deliberately built a routine around a local bakery, a park and a weekend language club.", "Yerleşmiş hissetmeyi beklemek yerine yerel bir fırın, park ve hafta sonu dil kulübü etrafında bilinçli bir rutin kurdu."), VocabItem("continuity", "devamlılık", "Those repeated encounters gave the city a sense of continuity.", "Bu tekrarlanan karşılaşmalar şehre bir devamlılık hissi verdi.")),
            questions=listOf(PracticeQuestion("What is the story's main insight?", listOf("Cities are expensive", "Belonging can be built through routines", "Moving is always a mistake", "Language clubs are boring"), 1, "Son cümle ana fikri açıkça veriyor.", "story comprehension"))
        ),
        Story(
            id="c1-city", level=CefrLevel.C1, title="The Architecture of Belonging", category="Şehir & Yaşam", emoji="🏙️", description="C1 seviyesinde şehir ve aidiyet temalı okuma.",
            sentences=listOf(StorySentence("Leo had assumed familiarity would emerge naturally once the boxes were unpacked.", "Leo kutular açıldığında aşinalığın doğal biçimde ortaya çıkacağını sanmıştı."), StorySentence("Instead, the city remained technically convenient but emotionally anonymous.", "Bunun yerine şehir teknik olarak kullanışlı ama duygusal olarak anonim kaldı."), StorySentence("He began to notice that attachment grew through repetition: the baker who recognized him, the same bench in the park, the people who expected him at a Saturday conversation group.", "Bağlılığın tekrar yoluyla büyüdüğünü fark etmeye başladı: onu tanıyan fırıncı, parktaki aynı bank, cumartesi konuşma grubunda onu bekleyen insanlar."), StorySentence("None of these moments was significant alone.", "Bu anların hiçbiri tek başına önemli değildi."), StorySentence("Together, however, they formed a quiet architecture of belonging.", "Ama birlikte sessiz bir aidiyet mimarisi oluşturdular.")),
            vocabulary=listOf(VocabItem("anonymous", "anonim/yabancı", "Instead, the city remained technically convenient but emotionally anonymous.", "Bunun yerine şehir teknik olarak kullanışlı ama duygusal olarak anonim kaldı."), VocabItem("attachment", "bağlılık", "He began to notice that attachment grew through repetition: the baker who recognized him, the same bench in the park, the people who expected him at a Saturday conversation group.", "Bağlılığın tekrar yoluyla büyüdüğünü fark etmeye başladı: onu tanıyan fırıncı, parktaki aynı bank, cumartesi konuşma grubunda onu bekleyen insanlar."), VocabItem("significant", "önemli", "None of these moments was significant alone.", "Bu anların hiçbiri tek başına önemli değildi.")),
            questions=listOf(PracticeQuestion("What does 'architecture of belonging' refer to?", listOf("Buildings", "A network of repeated small experiences", "City planning", "His apartment"), 1, "Metafor, küçük tekrarların birlikte aidiyet oluşturmasını anlatıyor.", "story comprehension"))
        ),
        Story(
            id="c2-city", level=CefrLevel.C2, title="A City Becomes Legible", category="Şehir & Yaşam", emoji="🏙️", description="C2 seviyesinde şehir ve aidiyet temalı okuma.",
            sentences=listOf(StorySentence("For the first few weeks, the city presented itself to Leo as information rather than experience: routes, prices, opening hours, unfamiliar names.", "İlk birkaç hafta şehir Leo’ya deneyimden çok bilgi olarak görünüyordu: rotalar, fiyatlar, açılış saatleri, yabancı isimler."), StorySentence("Gradually, repetition converted geography into memory.", "Yavaş yavaş tekrar, coğrafyayı hafızaya dönüştürdü."), StorySentence("A bakery ceased to be merely a shop once someone there knew his order; a park acquired emotional coordinates when a particular bench became his place to think.", "Bir fırın, biri siparişini bildiğinde sadece dükkân olmaktan çıktı; belirli bir bank onun düşünme yeri olduğunda park duygusal koordinatlar kazandı."), StorySentence("The city had not objectively changed, yet it had become legible in a deeper sense.", "Şehir nesnel olarak değişmemişti ama daha derin bir anlamda okunabilir hale gelmişti."), StorySentence("Belonging was, perhaps, the slow conversion of public space into personal meaning.", "Aidiyet belki de kamusal alanın kişisel anlama yavaş dönüşmesiydi.")),
            vocabulary=listOf(VocabItem("legible", "okunabilir/anlaşılır", "The city had not objectively changed, yet it had become legible in a deeper sense.", "Şehir nesnel olarak değişmemişti ama daha derin bir anlamda okunabilir hale gelmişti."), VocabItem("ceased", "olmaktan çıktı", "A bakery ceased to be merely a shop once someone there knew his order; a park acquired emotional coordinates when a particular bench became his place to think.", "Bir fırın, biri siparişini bildiğinde sadece dükkân olmaktan çıktı; belirli bir bank onun düşünme yeri olduğunda park duygusal koordinatlar kazandı."), VocabItem("coordinates", "koordinatlar", "A bakery ceased to be merely a shop once someone there knew his order; a park acquired emotional coordinates when a particular bench became his place to think.", "Bir fırın, biri siparişini bildiğinde sadece dükkân olmaktan çıktı; belirli bir bank onun düşünme yeri olduğunda park duygusal koordinatlar kazandı.")),
            questions=listOf(PracticeQuestion("What does 'geography into memory' suggest?", listOf("He memorised a map", "Places gained personal associations", "He studied geography", "He forgot routes"), 1, "Mekânlar kişisel anılar ve anlamlar kazandı.", "story comprehension"))
        ),
        Story(
            id="a1-dog", level=CefrLevel.A1, title="The Friendly Dog", category="Macera", emoji="🐶", description="Basit bir park hikâyesi.",
            sentences=listOf(StorySentence("Ada walks in the park.", "Ada parkta yürür."), StorySentence("A small dog follows her.", "Küçük bir köpek onu takip eder."), StorySentence("The dog has no owner near it.", "Yakında sahibini göremez."), StorySentence("Ada reads the phone number on its tag.", "Ada tasmasındaki telefon numarasını okur."), StorySentence("Soon, the owner comes and says thank you.", "Kısa süre sonra sahibi gelir ve teşekkür eder.")),
            vocabulary=listOf(VocabItem("follow", "takip etmek", "A small dog follows her.", "Küçük bir köpek onu takip eder."), VocabItem("owner", "sahip", "The dog has no owner near it.", "Yakında sahibini göremez."), VocabItem("tag", "künyesi/etiketi", "Ada reads the phone number on its tag.", "Ada tasmasındaki telefon numarasını okur.")),
            questions=listOf(PracticeQuestion("What does Ada use to contact the owner?", listOf("A map", "The tag", "A shop", "A bus"), 1, "Köpeğin künyesindeki numarayı kullanır.", "story comprehension"))
        ),
        Story(
            id="a2-train", level=CefrLevel.A2, title="The Wrong Train", category="Seyahat", emoji="🚆", description="Küçük bir seyahat hatası.",
            sentences=listOf(StorySentence("Emre was travelling to Bristol for a meeting.", "Emre toplantı için Bristol’e gidiyordu."), StorySentence("He was in a hurry and got on the wrong train.", "Acelesi vardı ve yanlış trene bindi."), StorySentence("After twenty minutes, he noticed the station names were unfamiliar.", "Yirmi dakika sonra istasyon isimlerinin yabancı olduğunu fark etti."), StorySentence("He asked a conductor for help.", "Görevliden yardım istedi."), StorySentence("The conductor showed him where to change trains.", "Görevli nerede tren değiştireceğini gösterdi."), StorySentence("Emre arrived late, but with a good story.", "Emre geç vardı ama anlatacak iyi bir hikâyesi vardı.")),
            vocabulary=listOf(VocabItem("hurry", "acele", "He was in a hurry and got on the wrong train.", "Acelesi vardı ve yanlış trene bindi."), VocabItem("unfamiliar", "yabancı/tanıdık olmayan", "After twenty minutes, he noticed the station names were unfamiliar.", "Yirmi dakika sonra istasyon isimlerinin yabancı olduğunu fark etti."), VocabItem("conductor", "tren görevlisi", "He asked a conductor for help.", "Görevliden yardım istedi.")),
            questions=listOf(PracticeQuestion("What was Emre's mistake?", listOf("He lost his bag", "He took the wrong train", "He missed the meeting place", "He forgot money"), 1, "Yanlış trene bindi.", "story comprehension"))
        ),
        Story(
            id="b1-neighbour", level=CefrLevel.B1, title="The New Neighbour", category="Arkadaşlık", emoji="🏠", description="Günlük hayatta yeni bir tanışma.",
            sentences=listOf(StorySentence("Nora had lived in the building for years, but rarely spoke to her neighbours.", "Nora yıllardır binada yaşıyordu ama komşularıyla nadiren konuşuyordu."), StorySentence("One rainy evening, a new neighbour knocked on her door because his internet was not working.", "Yağmurlu bir akşam yeni komşusu interneti çalışmadığı için kapısını çaldı."), StorySentence("Nora could not fix it, but offered him tea while he called the provider.", "Nora düzeltemedi ama sağlayıcıyı ararken ona çay teklif etti."), StorySentence("A small favour turned into a long conversation.", "Küçük bir iyilik uzun bir sohbete dönüştü."), StorySentence("A week later, they were having dinner together with other neighbours.", "Bir hafta sonra diğer komşularla birlikte akşam yemeği yiyorlardı.")),
            vocabulary=listOf(VocabItem("rarely", "nadiren", "Nora had lived in the building for years, but rarely spoke to her neighbours.", "Nora yıllardır binada yaşıyordu ama komşularıyla nadiren konuşuyordu."), VocabItem("provider", "hizmet sağlayıcı", "Nora could not fix it, but offered him tea while he called the provider.", "Nora düzeltemedi ama sağlayıcıyı ararken ona çay teklif etti."), VocabItem("favour", "iyilik", "A small favour turned into a long conversation.", "Küçük bir iyilik uzun bir sohbete dönüştü.")),
            questions=listOf(PracticeQuestion("What started their friendship?", listOf("A party", "An internet problem", "A job", "A pet"), 1, "İnternet sorunu nedeniyle kapı çalındı.", "story comprehension"))
        ),
        Story(
            id="b2-interview", level=CefrLevel.B2, title="The Interview That Changed Direction", category="İş Hayatı", emoji="💼", description="Beklenmedik bir iş görüşmesi.",
            sentences=listOf(StorySentence("Selin had prepared carefully for a conventional interview.", "Selin geleneksel bir iş görüşmesine dikkatle hazırlanmıştı."), StorySentence("Instead, the interviewer spent most of the time asking about a volunteer project mentioned at the bottom of her CV.", "Bunun yerine görüşmeci zamanın çoğunu CV’nin altındaki gönüllü projeyi sorarak geçirdi."), StorySentence("At first, Selin worried that the conversation had gone off track.", "Başta Selin konuşmanın konudan saptığından endişelendi."), StorySentence("Then she realised the interviewer was testing how she handled uncertainty and explained decisions.", "Sonra görüşmecinin belirsizlikle nasıl baş ettiğini ve kararları nasıl açıkladığını test ettiğini fark etti."), StorySentence("She stopped giving rehearsed answers and began speaking more naturally.", "Ezber cevaplar vermeyi bırakıp daha doğal konuşmaya başladı."), StorySentence("That change probably did more for her than all the preparation.", "Bu değişiklik muhtemelen tüm hazırlıktan daha çok işine yaradı.")),
            vocabulary=listOf(VocabItem("conventional", "geleneksel", "Selin had prepared carefully for a conventional interview.", "Selin geleneksel bir iş görüşmesine dikkatle hazırlanmıştı."), VocabItem("off track", "konudan sapmış", "At first, Selin worried that the conversation had gone off track.", "Başta Selin konuşmanın konudan saptığından endişelendi."), VocabItem("rehearsed", "ezberlenmiş/prova edilmiş", "She stopped giving rehearsed answers and began speaking more naturally.", "Ezber cevaplar vermeyi bırakıp daha doğal konuşmaya başladı.")),
            questions=listOf(PracticeQuestion("Why did the interview focus on the volunteer project?", listOf("To waste time", "To test broader skills", "Because the CV was wrong", "To end early"), 1, "Belirsizlik ve karar açıklama becerisini görmek istiyordu.", "story comprehension"))
        ),
        Story(
            id="c1-silence", level=CefrLevel.C1, title="The Useful Silence", category="İletişim", emoji="🤫", description="Konuşmada sessizliğin işlevi.",
            sentences=listOf(StorySentence("During negotiations, Arda used to treat every silence as a problem that needed filling.", "Arda müzakerelerde her sessizliği doldurulması gereken bir sorun olarak görürdü."), StorySentence("He would rush to add explanations, often weakening a point he had already made clearly.", "Açıklama eklemek için acele eder, çoğu zaman zaten net söylediği bir noktayı zayıflatırdı."), StorySentence("A more experienced colleague suggested an experiment: make the point, then wait.", "Daha deneyimli bir meslektaşı bir deney önerdi: fikri söyle, sonra bekle."), StorySentence("The result surprised him.", "Sonuç onu şaşırttı."), StorySentence("Silence gave other people room to think and often encouraged them to reveal more.", "Sessizlik diğer insanlara düşünme alanı verdi ve çoğu zaman daha fazla şey açıklamalarını teşvik etti."), StorySentence("Arda learned that fluent communication was not the same as continuous speech.", "Arda akıcı iletişimin kesintisiz konuşmakla aynı şey olmadığını öğrendi.")),
            vocabulary=listOf(VocabItem("negotiation", "müzakere", "During negotiations, Arda used to treat every silence as a problem that needed filling.", "Arda müzakerelerde her sessizliği doldurulması gereken bir sorun olarak görürdü."), VocabItem("weaken", "zayıflatmak", "He would rush to add explanations, often weakening a point he had already made clearly.", "Açıklama eklemek için acele eder, çoğu zaman zaten net söylediği bir noktayı zayıflatırdı."), VocabItem("reveal", "açığa çıkarmak", "Silence gave other people room to think and often encouraged them to reveal more.", "Sessizlik diğer insanlara düşünme alanı verdi ve çoğu zaman daha fazla şey açıklamalarını teşvik etti.")),
            questions=listOf(PracticeQuestion("What did Arda learn?", listOf("Silence always means failure", "Good communication can include silence", "Negotiations should be fast", "Long explanations are best"), 1, "Son cümle bunu vurgular.", "story comprehension"))
        ),
        Story(
            id="c2-memory", level=CefrLevel.C2, title="The Unreliable Photograph", category="Psikoloji", emoji="📷", description="Hafıza ve anlatı üzerine ileri okuma.",
            sentences=listOf(StorySentence("Years later, Leyla discovered that one of her clearest childhood memories could not have happened as she remembered it.", "Yıllar sonra Leyla en net çocukluk anılarından birinin hatırladığı gibi gerçekleşmiş olamayacağını keşfetti."), StorySentence("A photograph she had always believed documented the event had been taken two years later.", "Olayı belgelediğine inandığı fotoğraf iki yıl sonra çekilmişti."), StorySentence("The discovery did not erase the memory; it made it more interesting.", "Keşif anıyı silmedi; daha ilginç hale getirdi."), StorySentence("She began to wonder how much of remembering was retrieval and how much was reconstruction.", "Hatırlamanın ne kadarının geri çağırma, ne kadarının yeniden kurma olduğunu merak etmeye başladı."), StorySentence("Perhaps memory was less an archive than a story repeatedly edited by the present.", "Belki hafıza bir arşivden çok şimdiki zaman tarafından tekrar tekrar düzenlenen bir hikâyeydi.")),
            vocabulary=listOf(VocabItem("document", "belgelemek", "A photograph she had always believed documented the event had been taken two years later.", "Olayı belgelediğine inandığı fotoğraf iki yıl sonra çekilmişti."), VocabItem("retrieval", "geri çağırma", "She began to wonder how much of remembering was retrieval and how much was reconstruction.", "Hatırlamanın ne kadarının geri çağırma, ne kadarının yeniden kurma olduğunu merak etmeye başladı."), VocabItem("reconstruction", "yeniden kurma", "She began to wonder how much of remembering was retrieval and how much was reconstruction.", "Hatırlamanın ne kadarının geri çağırma, ne kadarının yeniden kurma olduğunu merak etmeye başladı.")),
            questions=listOf(PracticeQuestion("What is the central idea?", listOf("Photos are always false", "Memory may be reconstructed over time", "Childhood is unimportant", "Archives are useless"), 1, "Son iki cümle hafızanın yeniden kurulabileceğini tartışıyor.", "story comprehension"))
        )
    )
    fun forLevel(level: CefrLevel): List<Story> = stories.filter { it.level == level }
    fun categories(): List<String> = stories.map { it.category }.distinct()
}